In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
df=pd.read_csv('/content/drive/MyDrive/Omdena Fresh water/Dataset/موارد المياه العذبة المتجددة - Sheet1.csv')

In [4]:
df.head()

   الخط                                              الفئة  ... 2018  2019
0     1                                             الهطول  ...  NaN   NaN
1     2                                       البخر الفعلي  ...  NaN   NaN
2     3                              التدفق الداخلي =)1-2(  ...  NaN   NaN
3     4  التدفق الداخل للمياه السطحية والمياه الجوفية م...  ...  NaN   NaN
4     5                موارد المياه العذبة المتجددة =)3+4(  ...  NaN   NaN

[5 rows x 26 columns]

In [5]:
df.columns

Index(['الخط', 'الفئة', 'الوحدة', 'المتوسط السنوي في الأجل الطويل', '1990',
       '1995', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019'],
      dtype='object')

In [18]:
df['الفئة'].unique()

array(['الهطول', 'البخر الفعلي', 'التدفق الداخلي =)1-2(',
       'التدفق الداخل للمياه السطحية والمياه الجوفية من البلدان المجاورة',
       'موارد المياه العذبة المتجددة =)3+4(',
       'التدفقات الخارجة للمياه السطحية والمياه الجوفية إلى البلدان المجاورة',
       ' ومنها:\n     المكفول بمعاهدات', '     غير المكفول بمعاهدات',
       'التدفق الخارج للمياه السطحية والمياه الجوفية إلى البحار'],
      dtype=object)

In [16]:
Precipitation_df=df.loc[df['الفئة']=='الهطول' ]

In [17]:
Precipitation_df.head()

   الخط   الفئة                   الوحدة  ...  2017  2018  2019
0     1  الهطول  مليون متر مكعب في السنة  ...   NaN   NaN   NaN

[1 rows x 26 columns]

In [19]:
Actual_evapotranspiration_df=df.loc[df['الفئة']=='البخر الفعلي' ]

In [20]:
Actual_evapotranspiration_df

   الخط         الفئة                   الوحدة  ...  2017  2018  2019
1     2  البخر الفعلي  مليون متر مكعب في السنة  ...   NaN   NaN   NaN

[1 rows x 26 columns]